---
title: "Knowledge and Visual Analytics"
author: "Walt Wells, Fall 2017"
subtitle: "Final Project Proposal"
output:
  html_document:
    css: ../custom.css
    highlight: zenburn
    theme: lumen
---

# Idea

Create a visualization that shows gun violence in the US from 2014-2017 using data curated by the Gun Violence Archive.  

# Data Source(s)

[The Gun Violence Archive](http://www.gunviolencearchive.org/methodology)

The archive provides some data sets for downlown via their website.  I was able to obtain 2014-2017 data on Mass Shootings.   There are about ~1100 observations in this aggregated dataset.   Mass Shootings are defined in the following way: 

>  GVA uses a purely statistical threshold to define mass shooting based ONLY on the numeric value of 4 or more shot or killed, not including the shooter. GVA does not parse the definition to remove any subcategory of shooting. To that end we don’t exclude, set apart, caveat, or differentiate victims based upon the circumstances in which they were shot.

I think it would be very interesting to also look beyond mass shootings and review data at the incident level.   Through the contact forms and email, I have reached out to request access to data at the incident level.   Should permission be granted, this would drastically increase the number of observations, as a brief skim of the last 72 hours of incidents is roughly 300 observations. 

# Data Citation

[Gun Violence Archive](http://www.gunviolencearchive.org/about) Mission Statement:

> Gun Violence Archive (GVA) is a not for profit corporation formed in 2013 to provide online public access to accurate information about gun-related violence in the United States. GVA will collect and check for accuracy, comprehensive information about gun-related violence in the U.S. and then post and disseminate it online, primarily if not exclusively on this website and summary ledgers at www.facebook.com/gunviolencearchive. It is hoped that this information will inform and assist those engaged in discussions and activities concerning gun violence, including analysis of proposed regulations or legislation relating to gun safety usage. All we ask is to please provide proper credit for use of Gun Violence Archive data and advise us of its use.

> GVA is not, by design an advocacy group. The mission of GVA is to document incidents of gun violence and gun crime nationally to provide independent, verified data to those who need to use it in their research, advocacy or writing.

# Toolset

This project will be managed in R.   I'd like to explore using `leaflet` for the first time and will also be exploring R libraries for handling geospatial data like `sp`, `maptools`, `rgdal`, `mapview`, `gmap`, `mapmate`, and `rgeos`.

I expect to take the street addresses provided in the dataset and query the google API for lat/lon using `ggmap`. 

I hope to animate the map to plot time using the `gganimate`, `animation`, `mapmate` or another similar package. 

# Project Delivery

Either a ShinyR app or an animated and interactive image (depending on how much user interactivity is relevant) that gives the viewer a better understanding of gun violence or mass shootings in the US.  
